services:
  backend:
    build:
      context: ./backend
    container_name: acegrad-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./Client
    container_name: acegrad-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped