import mongoose from "mongoose";

/**
 * @description Interview Session Schema - Handles the entire lifecycle of an AI interview.
 * Tracks candidate details, AI-generated questions, user submissions, and final AI reports.
 * Fully optimized to support both Self-Practice (B2C) and Recruiter Campaigns (B2B).
 */
const interviewSchema = new mongoose.Schema(
  {
    // 1. Relational Mapping: Identifies which logged-in user (Candidate or Recruiter) owns this interview session
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User", // Dynamic lookup pointer referencing the User Model
      required: [true, "An interview session must belong to a user"],
    },

    // 🆕 2. System Mode Configuration: Differentiates between self-practice and recruiter campaigns
    interviewType: {
      type: String,
      enum: ["practice", "campaign"], // practice = Candidate self test, campaign = Recruiter shareable job link
      default: "practice",
    },

    // 🆕 3. Guest Candidate Data: Captures external user identity when filling out a recruiter's link
    candidateName: {
      type: String,
      trim: true,
    },
    candidateEmail: {
      type: String,
      trim: true,
      lowercase: true,
    },
    // model/interview.model.js ke andar candidateEmail ke niche add karo:
    accessOtp: {
      type: String,
      trim: true,
    },
    // 4. Candidate Context Data: Captured from frontend inputs to feed into Gemini AI
    jobTitle: {
      type: String,
      required: [true, "Job title / role is required"],
      trim: true, // Auto-removes accidental whitespaces from input boundaries
    },
    jobDescription: {
      type: String,
      required: [
        true,
        "Job description is required to generate tailored AI questions",
      ],
    },

    // 5. AI Pipeline Engine Data: Stores the customized 5 technical questions generated by Gemini
    questions: {
      type: [String], // Array of strings holding raw question texts
      required: [true, "AI generated questions are required"],
    },

    // 6. Submission Array: Tracks active candidate answers mapped directly back to their parent questions
    answers: [
      {
        questionIndex: { type: Number, required: true }, // Positional marker (0-4) inside the array
        questionText: { type: String, required: true }, // Snapshot of the original question asked
        userAnswer: { type: String, required: true }, // Core string data submitted by the user
      },
    ],

    // 7. Post-Interview Analytics Engine: Populated by Gemini after calling the /endInterview routine
    evaluation: {
      overallScore: { type: Number }, // Macro grading scale indicator (typically out of 10)
      feedbackSummary: { type: String }, // Editorial paragraphs outlining technical performance metrics
      skillsAssessment: { type: [String] }, // Granular metric tags (e.g., ["Strong: Node.js core", "Weak: Indexing schemas"])
    },

    // 8. Meta Tagging Data: Fallback descriptor matrix to tag specific technologies checked out
    techStack: {
      type: [String],
      default: [], // Starts as empty array so runtime creation validations don't block request threads
    },

    // 9. Status State Tracker: Manages routing gatekeepers and prevents double-evaluating past session IDs
    status: {
      type: String,
      enum: ["pending", "active", "completed"], // Rigid status boundary matrix
      default: "pending",
    },
  },
  {
    // Auto-generates indexed fields for createdAt and updatedAt timestamps inside MongoDB documents
    timestamps: true,
  },
);

const Interview = mongoose.model("Interview", interviewSchema);
export default Interview;
